### ISSUE TITLE
npm i does not work, resolve errors 

### ISSUE THREAD

**Issue by Arch881010** [botii16/funky-portfolio#1]
Hello!

When I run `npm i` or `npm run dev` in both a github codespace and on my laptop, I get an error stating that multiple things are unresolveable.

<details><summary>EResolve Log</summary>
<p>
'Log files:
/home/codespace/.npm/_logs/2024-11-22T22_13_22_902Z-debug-0.log

# npm resolution error report

While resolving: framer-motion@11.11.17
Found: react@19.0.0-rc-66855b96-20241106
node_modules/react
  react@"19.0.0-rc-66855b96-20241106" from the root project
  peer react@"^16.5.1 || ^17.0.0 || ^18.0.0 || ^19.0.0-rc" from lucide-react@0.460.0
  node_modules/lucide-react
    lucide-react@"^0.460.0" from the root project
  peer react@"^18.2.0 || 19.0.0-rc-66855b96-20241106" from next@15.0.3
  node_modules/next
    next@"15.0.3" from the root project
  peer react@"19.0.0-rc-66855b96-20241106" from react-dom@19.0.0-rc-66855b96-20241106
  node_modules/react-dom
    react-dom@"19.0.0-rc-66855b96-20241106" from the root project
    peer react-dom@"^18.2.0 || 19.0.0-rc-66855b96-20241106" from next@15.0.3
    node_modules/next
      next@"15.0.3" from the root project
  peer react@">= 16.8.0 || 17.x.x || ^18.0.0-0 || ^19.0.0-0" from styled-jsx@5.1.6
  node_modules/styled-jsx
    styled-jsx@"5.1.6" from next@15.0.3
    node_modules/next
      next@"15.0.3" from the root project

Could not resolve dependency:
peerOptional react@"^18.0.0" from framer-motion@11.11.17
node_modules/framer-motion
  framer-motion@"^11.11.17" from the root project

Conflicting peer dependency: react@18.3.1
node_modules/react
  peerOptional react@"^18.0.0" from framer-motion@11.11.17
  node_modules/framer-motion
    framer-motion@"^11.11.17" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

</p>
</details> 

<details><summary>Debug Log</summary>
<p>

# (header for formatting - this line did not exist in the file)

1 verbose cli /usr/local/share/nvm/versions/node/v20.17.0/bin/node /home/codespace/nvm/current/bin/npm
1 info using npm@10.8.2
2 info using node@v20.17.0
3 silly config load:file:/usr/local/share/nvm/versions/node/v20.17.0/lib/node_modules/npm/npmrc
4 silly config load:file:/workspaces/funky-portfolio/.npmrc
5 silly config load:file:/home/codespace/.npmrc
6 silly config load:file:/usr/local/share/nvm/versions/node/v20.17.0/etc/npmrc
7 verbose title npm i
8 verbose argv "i"
9 verbose logfile logs-max:10 dir:/home/codespace/.npm/_logs/2024-11-22T22_13_22_902Z-
10 verbose logfile /home/codespace/.npm/_logs/2024-11-22T22_13_22_902Z-debug-0.log
11 silly packumentCache heap:2197815296 maxSize:549453824 maxEntrySize:274726912
12 silly logfile done cleaning log files
13 silly idealTree buildDeps
14 silly fetch manifest react@^18.0.0
15 silly packumentCache full:https://registry.npmjs.org/react cache-miss
16 http fetch GET 200 https://registry.npmjs.org/react 405ms (cache miss)
17 silly packumentCache full:https://registry.npmjs.org/react set size:undefined disposed:false
18 silly fetch manifest react-dom@^18.0.0
19 silly packumentCache full:https://registry.npmjs.org/react-dom cache-miss
20 http fetch GET 200 https://registry.npmjs.org/react-dom 213ms (cache miss)
21 silly packumentCache full:https://registry.npmjs.org/react-dom set size:undefined disposed:false
22 verbose stack Error: could not resolve
22 verbose stack     at PlaceDep.failPeerConflict (/usr/local/share/nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:503:25)
22 verbose stack     at new PlaceDep (/usr/local/share/nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:157:21)
22 verbose stack     at #buildDepStep (/usr/local/share/nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:917:18)
22 verbose stack     at async Arborist.buildIdealTree (/usr/local/share/nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:181:7)
22 verbose stack     at async Promise.all (index 1)
22 verbose stack     at async Arborist.reify (/usr/local/share/nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:131:5)
22 verbose stack     at async Install.exec (/usr/local/share/nvm/versions/node/v20.17.0/lib/node_modules/npm/lib/commands/install.js:150:5)
22 verbose stack     at async Npm.exec (/usr/local/share/nvm/versions/node/v20.17.0/lib/node_modules/npm/lib/npm.js:207:9)
22 verbose stack     at async module.exports (/usr/local/share/nvm/versions/node/v20.17.0/lib/node_modules/npm/lib/cli/entry.js:74:5)
23 error code ERESOLVE
24 error ERESOLVE could not resolve
25 error
26 error While resolving: framer-motion@11.11.17
26 error Found: react@19.0.0-rc-66855b96-20241106[2m[22m
26 error [2mnode_modules/react[22m
26 error   react@"19.0.0-rc-66855b96-20241106" from the root project
26 error   [95mpeer[39m react@"^16.5.1 || ^17.0.0 || ^18.0.0 || ^19.0.0-rc" from lucide-react@0.460.0[2m[22m
26 error   [2mnode_modules/lucide-react[22m
26 error     lucide-react@"^0.460.0" from the root project
26 error   3 more (next, react-dom, styled-jsx)
26 error
26 error Could not resolve dependency:
26 error peerOptional react@"^18.0.0" from framer-motion@11.11.17[2m[22m
26 error [2mnode_modules/framer-motion[22m
26 error   framer-motion@"^11.11.17" from the root project
26 error
26 error Conflicting peer dependency: react@18.3.1[2m[22m
26 error [2mnode_modules/react[22m
26 error   peerOptional react@"^18.0.0" from framer-motion@11.11.17[2m[22m
26 error   [2mnode_modules/framer-motion[22m
26 error     framer-motion@"^11.11.17" from the root project
26 error
26 error Fix the upstream dependency conflict, or retry
26 error this command with --force or --legacy-peer-deps
26 error to accept an incorrect (and potentially broken) dependency resolution.
27 error
27 error
27 error For a full report see:
27 error /home/codespace/.npm/_logs/2024-11-22T22_13_22_902Z-eresolve-report.txt
28 silly unfinished npm timer reify 1732313604681
29 silly unfinished npm timer reify:loadTrees 1732313604686
30 silly unfinished npm timer idealTree:buildDeps 1732313604848
31 silly unfinished npm timer idealTree:node_modules/framer-motion 1732313604849
32 verbose cwd /workspaces/funky-portfolio
33 verbose os Linux 6.5.0-1025-azure
34 verbose node v20.17.0
35 verbose npm  v10.8.2
36 verbose exit 1
37 verbose code 1
38 error A complete log of this run can be found in: /home/codespace/.npm/_logs/2024-11-22T22_13_22_902Z-debug-0.log

</p>
</details>

**Comment by botii16** [comment]
### **Thank you for reporting this issue.**
I apologize for the inconvenience you're experiencing. Let me explain what's happening and provide some potential solutions.

The error you're encountering is due to a dependency conflict, specifically with the 'react' package. Here's a breakdown of the issue:
**1.** The project is using React version 19.0.0-rc (a release candidate), which is not yet stable.
**2.** Framer Motion (version 11.11.17) is expecting React version 18.x.
**3.** Other dependencies like Next.js and Lucide React are compatible with both React 18 and 19-rc, but the conflict arises with Framer Motion.

### **To resolve this issue**, you can try the following solutions (some source: Vercel's react.js docs):

**1.**: Use '--legacy-peer-deps' flag: `npm install --legacy-peer-deps`
_This will ignore peer dependency conflicts and install the packages anyway. However, this might lead to potential issues down the line._

**2.**: Downgrade React to version 18 _(the most safest option)_:
Update the `package.json` file to use React 18 instead of the release candidate: 
```
"dependencies": {
  "react": "^18.2.0",
  "react-dom": "^18.2.0"
}
```
Then run `npm install` again.

**3.**: Upgrade Framer Motion:
There might be a newer version of Framer Motion that supports React 19-rc. Try upgrading it:
`npm install framer-motion@latest`

**4.**: Use `--force` flag :
`npm install --force`

I recommend trying these solutions in the order presented. **Option 2 (downgrading React) is likely the safest** bet for now, as it ensures compatibility with all dependencies.

If you continue to face issues after trying these solutions, please let me know, and I'll be happy to help further. Also, could you please provide your `package.json` file? It would help me understand the exact versions of all dependencies and provide more targeted advice.

Thank you for your patience and for bringing this to my attention. I will get to work now on my side too to commit a right build.

**Comment by botii16** [comment]
Hello again, sorry for the lot of comments.
Managed to fix the issue now by degrading react from 19 to 18 and reversing layout.tsx from 'meta' to 'metadata'.
### **So now it should work perfectly.**
